name: "connectr-backend"


services:

  # Neo4j Database
  db:
    image: neo4j:5.21.2-community-bullseye
    restart: always
    env_file:
      - .env
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db:/data
      - vol:/var/lib/db/logs
      - vol:/var/lib/db/config
    # Simple check testing whether the port 7474 is opened.
    # If so, the instance running inside the container is considered as "healthy".
    healthcheck:
      test: ["CMD-SHELL", "wget --verbose --tries=1 --spider localhost:7474 || exit 1"]

  # Zookeeper for Kafka Setup
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Kafka for Message Queue
  kafka:
    image: 'bitnami/kafka:3.2'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
    depends_on:
      - zookeeper

  # ConnectR API
  api:
    build: .
    restart: always
    ports:
    - '9000:9000'
    container_name: api
    depends_on:
      - db
      - kafka
