// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abdullahnettoor/connect-social-media/internal/config"
	"github.com/abdullahnettoor/connect-social-media/internal/infrastructure/db"
	"github.com/abdullahnettoor/connect-social-media/internal/infrastructure/server"
	"github.com/abdullahnettoor/connect-social-media/internal/infrastructure/server/handlers"
	"github.com/abdullahnettoor/connect-social-media/internal/repo"
	"github.com/abdullahnettoor/connect-social-media/internal/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config) (*server.ServeHttp, error) {
	driverWithContext, err := db.ConnectDb(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repo.NewUserRepository(driverWithContext)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handlers.NewUserHandler(userUseCase)
	adminRepository := repo.NewAdminRepository(driverWithContext)
	adminUseCase := usecase.NewAdminUseCase(adminRepository, userRepository)
	adminHandler := handlers.NewAdminHandler(adminUseCase)
	serveHttp := server.NewServeHttp(userHandler, adminHandler)
	return serveHttp, nil
}
